Users is satisfactory
charlesjhill/UCBearcatBandsApp pull request #19
Opened 2019-06-14 00:41 UTC by charlesjhill

What's up y'all; Users is now is now in a good enough place that' I'm willing to merge. Here's the new api routes and a brief description of what they do.

/api/v1/ <- API is now versioned
      students/ <- our students are here
      users/      <- ALL our users (students and admins) are here
      rest-auth/ <- home to all things authentication
            login/  <- You can login here. Posting to this with valid credentials yields a token
            logout/ <- Post to here to logout
            registration/ <- Post to here with some data to create a user; This will also yield a token

Logging in currently requires an email, username, and password. I'm planning to fix this to allow either OR both.

Registration requires a username, email, password1, password2, a boolean specifying if the user is a student, and a m_number, which only matters if is_student is true.

Currently, none of our views are protected, so you don't require a token to access them. This is also intended to change.

QED

2019-06-14 14:34 UTC, benhollar commented on DjangoBackend/ucbearcatbandsproject/bands/serializers.py
> +        fields = ('m_number', 'user',)
```suggestion
        fields = ('m_number', 'user',)
        
```

2019-06-14 14:34 UTC, benhollar commented on DjangoBackend/ucbearcatbandsproject/bands/urls.py
>  ]
```suggestion
]

```

2019-06-14 14:36 UTC, benhollar commented on DjangoBackend/ucbearcatbandsproject/users/admin.py
> +admin.site.register(CustomUser, CustomUserAdmin)
```suggestion
admin.site.register(CustomUser, CustomUserAdmin)

```

2019-06-14 14:37 UTC, benhollar commented on DjangoBackend/ucbearcatbandsproject/users/models.py
> +        return self.email
```suggestion
        return self.email
        
```

2019-06-14 14:38 UTC, benhollar commented on DjangoBackend/ucbearcatbandsproject/users/serializers.py
> +        return user
```suggestion
        return user
        
```

2019-06-14 14:39 UTC, benhollar requested changes
Hey fix the newlines

2019-06-17 18:13 UTC, benhollar approved these changes

2019-06-17 18:13 UTC, merged

2019-06-17 18:37 UTC, charlesjhill commented
:thumbsup: